version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run format

  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run test -u

  release:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - lint
      - test:
          requires:
            - lint
      - release:
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - lint
            - test
